#!/usr/bin/env python3
"""
Export chaos1 sklearn weights → C++ header for the Chaos2 instinct classifier.

Run from chaos1 directory (where the .pkl files live):
    python3 /path/to/chaos2/instinct/export_weights.py

Output: chaos2/instinct/model_weights.h
"""

import os
import pickle
import sys

try:
    with open("chaos_classifier.pkl", "rb") as f:
        clf = pickle.load(f)
    with open("chaos_vectorizer.pkl", "rb") as f:
        vec = pickle.load(f)
except FileNotFoundError as e:
    sys.exit(f"[export] {e}\nRun from the chaos1 directory.")

vocab     = vec.vocabulary_   # token → index
idf       = vec.idf_          # IDF per feature
coef      = clf.coef_         # (n_classes, n_features)
intercept = clf.intercept_    # (n_classes,)
classes   = [str(c) for c in clf.classes_]

n_classes, n_features = coef.shape

out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "model_weights.h")

with open(out, "w") as f:
    f.write("// AUTO-GENERATED by export_weights.py — DO NOT EDIT\n")
    f.write("#pragma once\n")
    f.write("#include <array>\n")
    f.write("#include <string>\n")
    f.write("#include <unordered_map>\n\n")

    f.write(f"static constexpr int N_CLASSES  = {n_classes};\n")
    f.write(f"static constexpr int N_FEATURES = {n_features};\n\n")

    # class names
    f.write("static const std::array<std::string, N_CLASSES> CLASS_NAMES = {{\n")
    for c in classes:
        f.write(f'    "{c}",\n')
    f.write("}};\n\n")

    # vocabulary
    f.write("static const std::unordered_map<std::string, int> VOCABULARY = {{\n")
    for token, idx in sorted(vocab.items(), key=lambda x: x[1]):
        esc = token.replace("\\", "\\\\").replace('"', '\\"')
        f.write(f'    {{"{esc}", {idx}}},\n')
    f.write("}};\n\n")

    # IDF
    f.write("static const std::array<double, N_FEATURES> IDF = {{\n    ")
    f.write(",\n    ".join(f"{v:.10f}" for v in idf))
    f.write("\n}};\n\n")

    # coefficients
    f.write("static const std::array<std::array<double, N_FEATURES>, N_CLASSES> COEF = {{{{\n")
    for row in coef:
        f.write("    {{")
        f.write(", ".join(f"{v:.10f}" for v in row))
        f.write("}},\n")
    f.write("}}}};\n\n")

    # intercepts
    f.write("static const std::array<double, N_CLASSES> INTERCEPT = {{\n    ")
    f.write(", ".join(f"{v:.10f}" for v in intercept))
    f.write("\n}};\n")

print(f"[export] {n_classes} classes · {n_features} features → {out}")
